
-- scripts/rbac_setup.sql
-- Sample Snowflake RBAC for secure access

CREATE ROLE IF NOT EXISTS ROLE_CLAIMS_READER;
CREATE ROLE IF NOT EXISTS ROLE_CLAIMS_WRITER;

GRANT USAGE ON WAREHOUSE {warehouse} TO ROLE ROLE_CLAIMS_WRITER;
GRANT USAGE ON DATABASE {database} TO ROLE ROLE_CLAIMS_WRITER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE {database} TO ROLE ROLE_CLAIMS_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {sales_schema} TO ROLE ROLE_CLAIMS_WRITER;

GRANT USAGE ON DATABASE {database} TO ROLE ROLE_CLAIMS_READER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE {database} TO ROLE ROLE_CLAIMS_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA {sales_schema} TO ROLE ROLE_CLAIMS_READER;

-- Future grants
GRANT SELECT ON FUTURE TABLES IN SCHEMA {sales_schema} TO ROLE ROLE_CLAIMS_READER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA {sales_schema} TO ROLE ROLE_CLAIMS_WRITER;
