
-- scripts/snowflake_cost_monitor.sql
-- Simple warehouse credit usage by day
SELECT
  START_TIME::DATE AS usage_date,
  WAREHOUSE_NAME,
  SUM(CREDITS_USED_COMPUTE + CREDITS_USED_CLOUD_SERVICES) AS credits_used
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY 1,2
ORDER BY 1 DESC, 2;
